// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    DragItem: typeof import('./components/Dnd/DragItem.vue')['default']
    DragObject: typeof import('./components/Dnd/DragObject.vue')['default']
    DragZone: typeof import('./components/Dnd/DragZone.vue')['default']
    FieldComponent: typeof import('./components/FieldList/FieldComponent.vue')['default']
    FieldLayout: typeof import('./components/FieldLayout.vue')['default']
    FieldList: typeof import('./components/FieldList/index.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
